name: PR status label

on:
  pull_request:
    types: ['labeled']

jobs:
  check_pr_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: cchantep/probot-pr-status-label@ghaction-1.0.x
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
